### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by ubun2Junky** [obaez/dentistsmile#1]
obaez;
Great job on the theme.  One of my favorite ones for Jekyll.  I'm having a hard time trying to get your theme to load correctly in my environment (I've attached a screenshot at the bottom).  I can only assume that I'm missing some requirements.  I know you mentioned that it partly runs on bootstrap, I'm was going to try to include it via CDN, but even that isn't helping.  Was wondering if you can perhaps point me in the right direction so I can get the theme loaded as you had intended it.  Thanks.

<img width="692" alt="screen shot 2015-11-08 at 3 55 55 pm" src="https://cloud.githubusercontent.com/assets/6493500/11023286/dedeea5e-8631-11e5-90aa-673c540fbe6c.png">

**Comment by obaez** [comment]
Hi,

Thank you, by looking at the screenshot I'm assuming there's some issues with the path so the css isn't loading. How is your _config file and what else did you change?

**Comment by obaez** [comment]
Actually, the css folder is not included, you have to compile to SCSS file to create it, I included a Gruntfile to do everything, but you can use whatever you want.

**Comment by ubun2Junky** [comment]
To outline my steps.  I simply cloned the github url to my test VM server running ubuntu 14.04.  The path to the cloned directory is ~/dentistsmile.  I haven't changed any of the files.  I wanted to get the theme working like in your demo before I made any changes of my own.  In order to troubleshoot I did delete the  _site folder and ran jekyll build to recreate the directory.  Upon inspection I did see that there was

**Comment by obaez** [comment]
Yes, you have to compile the main.scss file to css/main.css

**Comment by ubun2Junky** [comment]
I installed compass and sass compiled the code from _scss directory and now it works wonderfully.  I just thought that Jekyll for some reason would have taken care of compiling that.  Still new to jekyll, getting familiar with it's capabilities.  Thx for you for your patience and advice!  Saludos!
