### ISSUE TITLE
Can't get it to build

### ISSUE THREAD

**Issue by xapple** [obaez/dentistsmile#2]
Hi !

I think your dentistsmile theme is great !

But, I followed the documentation and typed `grunt serve` which resulted in the site not displaying correctly, like if it was without CSS:

![test](https://cloud.githubusercontent.com/assets/649288/11395801/62f52860-936d-11e5-80f2-a2e3cbbbfb28.png)

**Comment by hackhowtofaq** [comment]
Same here!

**Comment by xapple** [comment]
Seems like there is a `<link rel="stylesheet" href="/css/main.css">` line in the HTML, but the theme uses only SCSS...

**Comment by obaez** [comment]
You have to open a new tan on the console and enter grunt, that will compile the scss and create the css folder. There's no css folder on the repo, that's why it looks like there are no styles. You can compile it with the gruntfile or any other option you choose to.

**Comment by xapple** [comment]
Yes I opened an other bash session to run `grunt` but it doesn't seem to do anything with the SCSS. Here is the transcript from the session that runs `grunt serve`:

        xapple@blastocyst test.github.io (master) $ grunt serve
        Running "shell:jekyllServe" (shell) task
        Configuration file: /Users/xapple/repos/test.github.io/_config.yml
                    Source: /Users/xapple/repos/test.github.io
               Destination: /Users/xapple/repos/test.github.io/_site
         Incremental build: disabled. Enable with --incremental
              Generating...
                            done in 0.218 seconds.
         Auto-regeneration: enabled for '/Users/xapple/repos/test.github.io'
        Configuration file: /Users/xapple/repos/test.github.io/_config.yml
            Server address: http://127.0.0.1:4000/
          Server running... press ctrl-c to stop.

And the session that runs `grunt`, launched afterwards:

    xapple@blastocyst test.github.io (master) $ grunt
    Running "watch" task
    Waiting...

**Comment by obaez** [comment]
It's waiting for any changes. Open the main.scss file and save it. That should create the css folder. I'll make some adjustments to make it easier later, it seems many are having the same issue.

**Comment by xapple** [comment]
Yeah it's really not obvious how it works... No one has any reason to edit the `main.scss` file. Unless you explain what to do in the documentation it's a hard puzzle. I ended up reading about grunt and reading your grunt file. Then running this command helped:

     $ grunt concat uglify sass autoprefixer shell svgmin svgs tore

But I don't know many people who are ready to invest so much if it doesn't work right away.

**Comment by hackhowtofaq** [comment]
I ll try to migrate this in jekyll 3 with jekyll-assets.

Ty for the info xapple ;)

**Comment by xapple** [comment]
You're welcome ! If you find an elegant solution please post back here :+1:

**Comment by hackhowtofaq** [comment]
Ready https://github.com/hackhowtofaq/dentistsmile

I have added some instructions... plz check if all ok

You have to replace images with yours, since all images in `/images` folder are placeholdes...

**Comment by xapple** [comment]
Seems good ! I'll tell you if I find something else !
