### ISSUE TITLE
Email buttons are not clickable

### ISSUE THREAD

**Issue by xapple** [obaez/dentistsmile#4]
Hi ! I identified a small issue in your great theme. The contact photos reveal two buttons, one for the email and one for the telephone number. They display this information, but they are not clickable ! I think the e-mail should be a `<a href="mailto:john@example.com">` and the telephone can also be a `<a href="tel:+331234564">`. This scheme is supported in some places, notably on iOS.

**Comment by obaez** [comment]
It's not really an issue, but I had some time so I added it :)

**Comment by xapple** [comment]
Wow, that was really nice of you to answer -- and add this feature -- so quickly ! Thanks.
