### ISSUE TITLE
Facebook and twitter icons not showing in Safari

### ISSUE THREAD

**Issue by xapple** [obaez/dentistsmile#5]
I tested the website with the latest Chrome and latest Firefox, and it was fine. But with the latest Safari the small SVG icons in the footer for Facebook and Twitter are not visible. Any idea how to fix that ?

**Comment by obaez** [comment]
What OS are you using and what version of Safari is there an issue on?

**Comment by xapple** [comment]
OK I'm sorry about that, it was in fact just "Adblock plus"... embarrassing !
